// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSii43rtkI1s3sOINdBscmljeywSBMlyY',
    appId: '1:360074311940:web:c128d7d7388069f4423851',
    messagingSenderId: '360074311940',
    projectId: 'challenges-taski',
    authDomain: 'challenges-taski.firebaseapp.com',
    storageBucket: 'challenges-taski.firebasestorage.app',
    measurementId: 'G-9707EQ7EZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9F77x4gDvcwCB1ZxF62PviYzBajsfagE',
    appId: '1:360074311940:android:1476c26301a87de1423851',
    messagingSenderId: '360074311940',
    projectId: 'challenges-taski',
    storageBucket: 'challenges-taski.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjlyDCxZVCs60n2kIZ4zYfGHwgK5DzrSY',
    appId: '1:360074311940:ios:15c8176a2853acea423851',
    messagingSenderId: '360074311940',
    projectId: 'challenges-taski',
    storageBucket: 'challenges-taski.firebasestorage.app',
    iosBundleId: 'com.example.challengesTaski',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjlyDCxZVCs60n2kIZ4zYfGHwgK5DzrSY',
    appId: '1:360074311940:ios:d748965da14610a4423851',
    messagingSenderId: '360074311940',
    projectId: 'challenges-taski',
    storageBucket: 'challenges-taski.firebasestorage.app',
    iosBundleId: 'com.example.challengesTaski.RunnerTests',
  );
}
